### ISSUE TITLE
Question on Timeouts

### ISSUE THREAD

**Issue by weberjm** [ascorbic/sse-demo#1]
Thanks for this demo of SSEs in Netlify. I have a quick question about the lifecycle of the SSE here. Will it also timeout like other functions after 10 seconds? 

I have seen that your demo seems to run "indefinitely" but that might be due to your internal account settings. If I am on a free or paid plan with Netlify, will the function timeout and end the delivery of messages?

**Comment by ascorbic** [comment]
Hi. No, because it uses Edge Functions which aren't subject to the 10s timeout. Instead they have a 50ms *CPU* time limit. If they're waiting, no CPU time is being used and they can continue indefinitely. If you start doing computationally-intensive things then it may timeout.

**Comment by weberjm** [comment]
Understood. Thanks for the info!
